# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a661b6a2a4141be2e97212a071ce993ded1ba4845f7009efc1d7f2972eaa9d4fe1f891101562b3d201f72d1fb0ef02bbc4e7b85aa9fc3441b804c649389dee4

test:
  secret_key_base: 95701331ffd121801fa0814cbd8aa50a32870f1e09b350930b766db5f762750fd9067409c20e6a92ae240965ffbd9ab15106510c0fb8f8aca5d272b66270d96c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
